### ISSUE TITLE
cxxopts::OptionParseException deprecated in newest version of cxxopts

### ISSUE THREAD

**Issue by lovelacelee** [CJLove/config-cpp#12]
cxxopts::OptionParseException deprecated in newest version of cxxopts
cuase the compiling error as follow:
```shell
config-cpp.cpp: In member function ‘bool ConfigCpp::ConfigCpp::ReadInConfig()’:
config-cpp.cpp:176:27: error: ‘OptionParseException’ in namespace ‘cxxopts’ does not name a type
  176 |         } catch (cxxopts::OptionParseException &e) {
      |                           ^~~~~~~~~~~~~~~~~~~~
config-cpp.cpp:178:39: error: ‘e’ was not declared in this scope
  178 |             std::cout << "Error: " << e.what() << "\n";
      |                                       ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-predefined-identifier-outside-function’
```

**Comment by CJLove** [comment]
Thanks for the heads up! Will take a look when I have the chance; probably this weekend.

**Comment by CJLove** [comment]
Looks like this changed as of cxxopt v3.1.0. Next update will specify version 3.1.0 or later.

**Comment by CJLove** [comment]
Resolved by https://github.com/CJLove/config-cpp/commit/6788afaa9c488c2bdf169cf61f26ef9fd7e67c86. Requiring cxxopt v3.1.1 or later because v3.1.0 had an incorrect version number in its header.
