### ISSUE TITLE
Can't build without JSON support

### ISSUE THREAD

**Issue by nikcleju** [CJLove/config-cpp#13]
There is a stray  `jsonHandler.cpp` in `src/Makefile' which makes it impossible to build without the JSON library available:

```
set (config-cpp_SRC
    config-cpp.cpp
    jsonHandler.cpp    <-----
    util.cpp
    value.cpp
    event.cpp
    notification.cpp
    filesystemEvent.cpp
    inotify.cpp
)
```

**Comment by CJLove** [comment]
Thanks for the heads up. I'll take a look when I have the chance.

**Comment by CJLove** [comment]
Should be resolved with latest commit.
