### ISSUE TITLE
cxxopts version 1.2.0 is incorrectly listed in cmakefile

### ISSUE THREAD

**Issue by harold-kfuse** [CJLove/config-cpp#9]
```find_package(cxxopts 1.2.0 REQUIRED)```

cxxopts 1.2.0 is incompatible with the usage of Options::parse in config-cpp.cpp.

cxxopts v1.2.0 has return type of void for Options::parse
v2.0.0 and up has return type of ParseResult for Options::parse, which is what config-cpp needs.

**Comment by CJLove** [comment]
Thanks for noticing this!  Fixed in https://github.com/CJLove/config-cpp/commit/ee5e75035c845cc4a437cd38ef22e4148110091f
